services:
  client:
    container_name: jobber-client
    image: jobber-client/v1.0.0
    build:
      context: .
      dockerfile: Dockerfile.dev
    networks:
      - jobber_app
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules

networks:
  jobber_app:
    name: jobber_app
