FROM node:alpine

RUN apk update && apk add --no-cache nodejs && corepack enable
RUN addgroup jobber && adduser -S -G jobber notification

USER notification

WORKDIR /notification

COPY package.json tsconfig.json .npmrc ./
COPY src ./src
COPY tools ./tools

USER root

RUN chown -R notification:jobber .

USER notification

RUN ls -a
RUN pnpm install
RUN rm -f .npmrc

EXPOSE 4001

CMD [ "pnpm", "dev" ]