services:
  redis:
    extends:
      service: redis
      file: infra/docker/docker-compose-redis.yaml

  redis-commander:
    extends:
      service: redis-commander
      file: infra/docker/docker-compose-redis.yaml

  mongodb:
    extends:
      service: mongodb
      file: infra/docker/docker-compose-mongodb.yaml

  mysql:
    extends:
      service: mysql
      file: infra/docker/docker-compose-mysql.yaml

  postgres:
    extends:
      service: postgres
      file: infra/docker/docker-compose-postgres.yaml

  rabbitmq:
    extends:
      service: rabbitmq
      file: infra/docker/docker-compose-rabbitmq.yaml

  elasticsearch:
    extends:
      service: elasticsearch
      file: infra/docker/docker-compose-elasticsearch.yaml

  kibana:
    extends:
      service: kibana
      file: infra/docker/docker-compose-kibana.yaml

  metricbeat:
    extends:
      service: metricbeat
      file: infra/docker/docker-compose-metricbeat.yaml

  heartbeat:
    extends:
      service: heartbeat
      file: infra/docker/docker-compose-heartbeat.yaml

  apmServer:
    extends:
      service: apmServer
      file: infra/docker/docker-compose-apm.yaml

  jenkins:
    extends:
      service: jenkins
      file: infra/docker/docker-compose-jenkins.yaml

  jenkins-agent:
    extends:
      service: jenkins-agent
      file: infra/docker/docker-compose-jenkins.yaml

  api-gateway:
    extends:
      service: api-gateway
      file: api/gateway/docker-compose.yaml

  notification:
    extends:
      service: notification
      file: api/notification/docker-compose.yaml

  authentication:
    extends:
      service: authentication
      file: api/authentication/docker-compose.yaml

  users:
    extends:
      service: users
      file: api/users/docker-compose.yaml

  gig:
    extends:
      service: gig
      file: api/gig/docker-compose.yaml

  chat:
    extends:
      service: chat
      file: api/chat/docker-compose.yaml

  order:
    extends:
      service: order
      file: api/order/docker-compose.yaml

  review:
    extends:
      service: review
      file: api/review/docker-compose.yaml

  client:
    extends:
      service: client
      file: client/docker-compose.yaml

volumes:
  mysql:
    name: mysql
  mongodb:
    name: mongodb
  redis:
    name: redis
  postgres:
    name: postgres
  elasticsearch:
    name: elasticsearch
  jenkins:
    name: jenkins

networks:
  elastic:
    name: elastic
  jobber_app:
    name: jobber_app
