FROM node:alpine

RUN apk update && apk add --no-cache nodejs && corepack enable
RUN addgroup jobber && adduser -S -G jobber order

USER order

WORKDIR /order

COPY package.json tsconfig.json .npmrc ./
COPY src ./src

USER root

RUN chown -R order:jobber .

USER order

RUN ls -a
RUN pnpm install
RUN rm -f .npmrc

EXPOSE 4006

CMD [ "pnpm", "dev" ]