version: "3.9"

include:
  - docker-compose-elasticsearch.yaml
  
services:
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.13.2
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]
    ports:
      - 5601:5601
    networks:
      - elastic
    volumes:
      - ./kibana.yaml/:/usr/share/kibana/config/kibana.yaml:ro
    depends_on:
      - elasticsearch
  networks:
    - elastic