version: '3.9'

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.4
    restart: always
    environment:
      ES_JAVA_OPTS: -Xmx2g -Xms2g
      bootstrap.memory_lock: 'true'
      discovery.type: 'single-node'
      xpack.security.enabled: 'false'
      xpack.security.authc.api_key.enabled: 'false'
      xpack.monitoring.collection.enabled: 'true'
      xpack.security.enrollment.enabled: 'false'
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:    
      resources:
          limits:
            cpus: '2.0'
          reservations:
            cpus: '1.0'
    networks:
      - elastic