services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    restart: always
    environment:
      ES_JAVA_OPTS: -Xmx1g -Xms1g
      ELASTIC_PASSWORD: admin1234
      discovery.type: single-node
      network.host: 0.0.0.0
      transport.host: 127.0.0.1
      http.host: 0.0.0.0
      bootstrap.memory_lock: 'true'
      xpack.security.enabled: 'false'
      xpack.security.authc.api_key.enabled: 'true'
      xpack.monitoring.collection.enabled: 'true'
      xpack.security.enrollment.enabled: 'true'
      xpack.security.authc.token.enabled: "true"
    ports:
      - 9300:9300
      - 9200:9200
    networks:
      - elastic
      - jobber_app
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    healthcheck:
        test: curl -s http://elasticsearch:9200 >/dev/null || exit 1
        interval: 30s
        timeout: 30s
        retries: 3
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          cpus: '2.0'
        reservations:
          cpus: '1.0'
