version: "3.9"

include:
  - docker-compose-elasticsearch.yaml
  
services:
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.11.4
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]
    ports:
      - 5601:5601
    networks:
      - elastic
    volumes:
      - ./kibana.yaml/:/usr/share/kibana/config/kibana.yaml:ro
    deploy:    
    resources:
        limits:
          cpus: '2.0'
        reservations:
          cpus: '1.0'
    depends_on:
      - elasticsearch 