services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'jobber_auth'
      MYSQL_USER: 'jobber'
      MYSQL_PASSWORD: 'api'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql
    networks:
     - jobber_app

volumes:
  mysql:
    name: mysql