heartbeat.config.monitors:
  path: ${path.config}/monitors.d/*.yml
  reload.enabled: false
  reload.period: 5s

heartbeat.monitors:
  - type: http
    id: api-gateway
    name: Jobber API Gateway Service
    schedule: '@every 15s'
    hosts: ['http://api-gateway:4000/gateway-health']
    check.request.method: GET
    check.response.status: [200]

  - type: http
    id: notification
    name: Jobber Notification Service
    schedule: '@every 15s'
    hosts: ['http://notification:4001/notification-health']
    check.request.method: GET
    check.response.status: [200]

  - type: http
    id: authentication
    name: Jobber Auth Service
    schedule: '@every 15s'
    hosts: ['http://authentication:4002/authentication-health']
    check.request.method: GET
    check.response.status: [200]

  - type: http
    id: users
    name: Jobber Users Service
    schedule: '@every 15s'
    hosts: ['http://users:4003/user-health']
    check.request.method: GET
    check.response.status: [200]

  - type: http
    id: gigs
    name: Jobber Gigs Service
    schedule: '@every 15s'
    hosts: ['http://gig:4004/gig-health']
    check.request.method: GET
    check.response.status: [200]

  - type: http
    id: chat
    name: Jobber Chat Service
    schedule: '@every 15s'
    hosts: ['http://chat:4005/chat-health']
    check.request.method: GET
    check.response.status: [200]

  - type: http
    id: orders
    name: Jobber Orders Service
    schedule: '@every 15s'
    hosts: ['http://order:4006/order-health']
    check.request.method: GET
    check.response.status: [200]

  - type: http
    id: reviews
    name: Jobber Reviews Service
    schedule: '@every 15s'
    hosts: ['http://review:4007/review-health']
    check.request.method: GET
    check.response.status: [200]

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

monitoring.enabled: true

output.elasticsearch:
  hosts: ['http://elasticsearch:9200']
  username: 'elastic'
  password: 'admin1234'
