apiVersion: v1
kind: Service
metadata:
  name: jobber-mongodb
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: jobber-mongodb
  ports:
    - name: jobber-mongodb
      port: 27017
      targetPort: 27017
