apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jobber-mongodb
  namespace: production
spec:
  selector:
    matchLabels:
      app: jobber-mongodb
  serviceName: jobber-mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: jobber-mongodb
    spec:
      containers:
        - name: jobber-mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
              name: jobber-mongodb
          volumeMounts:
            - name: mongo-local-storage
              mountPath: /data/db
      volumes:
        - name: mongo-local-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
