services:
  authentication:
    container_name: authentication
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4002:4002
    environment:
      - ENABLE_APM=0
      - GATEWAY_JWT_TOKEN=1282722b942e08c8a6cb033aa6ce850e
      - JWT_TOKEN=8db8f85991bb28f45ac0107f2a1b349c
      - NODE_ENV=development
      - SECRET_KEY_ONE=032c5c3cfc37938ae6dd43d3a3ec7834
      - SECRET_KEY_TWO=d66e377018c0bc0b5772bbc9b131e6d9
      - CLOUD_NAME=jobber-app
      - CLOUD_API_KEY=451681577626762
      - CLOUD_API_SECRET=zGY_r3M8pfcyhCP6VF10a0z04EY
      - CLIENT_URL=http://localhost:3000
      - AUTH_BASE_URL=http://localhost:4002
      - USERS_BASE_URL=http://localhost:4003
      - GIG_BASE_URL=http://localhost:4004
      - MESSAGE_BASE_URL=http://localhost:4005
      - ORDER_BASE_URL=http://localhost:4006
      - REVIEW_BASE_URL=http://localhost:4007
      - MYSQL_DB=mysql://jobber:api@mysql:3306/jobber_auth
      - REDIS_HOST=redis://redis_container:6379
      - RABBITMQ_ENDPOINT=amqp://jobber:jobberpass@rabbitmq:5672
      - ELASTIC_SEARCH_URL=http://elasticsearch:9200
      - ELASTIC_APM_SERVER_URL=http://localhost:8200
    depends_on:
      elasticsearch:
        condition: service_healthy
      mysql:
        condition: service_healthy
    healthcheck:
      test:  curl -f http://localhost:4002/authentication-health || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
    volumes:
      - .:/authentication
      - /authentication/node_modules
    networks:
      - jobber_app
