services:
  authentication:
    container_name: authentication
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4002:4002
    env_file: .env
    depends_on:
      elasticsearch:
        condition: service_healthy
      mysql:
        condition: service_healthy
    healthcheck:
      test: curl -f http://localhost:4002/authentication-health || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
    volumes:
      - .:/authentication
      - /authentication/node_modules
    networks:
      - jobber_app
