FROM node:alpine

RUN apk update && apk add --no-cache nodejs && corepack enable
RUN addgroup jobber && adduser -S -G jobber authentication

USER authentication

WORKDIR /authentication

COPY package.json tsconfig.json .npmrc ./
COPY prisma ./prisma
COPY src ./src

USER root

RUN chown -R authentication:jobber .

USER authentication

RUN ls -a
RUN pnpm install
RUN rm -f .npmrc

EXPOSE 4002

CMD [ "pnpm", "dev" ]

