FROM node:alpine

RUN apk update && apk add --no-cache nodejs && corepack enable
RUN addgroup jobber && adduser -S -G jobber authentication

USER authentication

WORKDIR /authentication

COPY package.json tsconfig.json .npmrc ./
COPY src ./src

RUN ls -a
RUN pnpm install

EXPOSE 4002

CMD [ "pnpm", "dev" ]

