services:
  gig:
    container_name: gig
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4004:4004
    env_file: .env.development.local
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: curl -f http://localhost:4004/gig-health || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
    volumes:
      - .:/gig
      - /gig/node_modules
    networks:
      - jobber_app
