FROM node:alpine

RUN apk update && apk add --no-cache nodejs && corepack enable
RUN addgroup jobber && adduser -S -G jobber chat

USER chat

WORKDIR /chat

COPY package.json tsconfig.json .npmrc ./
COPY src ./src

USER root

RUN chown -R chat:jobber .

USER chat

RUN ls -a
RUN pnpm install
RUN rm -f .npmrc

EXPOSE 4005

CMD [ "pnpm", "dev" ]

