services:
  chat:
    container_name: chat
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4005:4005
    env_file: .env.development.local
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: curl -f http://localhost:4005/chat-health || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
    volumes:
      - .:/chat
      - /chat/node_modules
    networks:
      - jobber_app
