FROM node:alpine

RUN apk update && apk add --no-cache nodejs && corepack enable
RUN addgroup jobber && adduser -S -G jobber review

USER review

WORKDIR /review

COPY package.json tsconfig.json .npmrc ./
COPY src ./src

USER root

RUN chown -R review:jobber .

USER review

RUN ls -a
RUN pnpm install
RUN rm -f .npmrc

EXPOSE 4007

CMD [ "pnpm", "dev" ]

