version: '3.9'

services:
  api-gateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4000:4000
    environment:
      - ENABLE_APM=0
      - GATEWAY_JWT_TOKEN=1282722b942e08c8a6cb033aa6ce850e
      - JWT_TOKEN=8db8f85991bb28f45ac0107f2a1b349c
      - NODE_ENV=development
      - SECRET_KEY_ONE=032c5c3cfc37938ae6dd43d3a3ec7834
      - SECRET_KEY_TWO=d66e377018c0bc0b5772bbc9b131e6d9
      - CLIENT_URL=http://localhost:3000
      - AUTH_BASE_URL=http://localhost:4002
      - USERS_BASE_URL=http://localhost:4003
      - GIG_BASE_URL=http://localhost:4004
      - MESSAGE_BASE_URL=http://localhost:4005
      - ORDER_BASE_URL=http://localhost:4006
      - REVIEW_BASE_URL=http://localhost:4007
      - REDIS_HOST=redis://redis_container:6379
      - ELASTIC_SEARCH_URL=http://elasticsearch:9200
      - ELASTIC_APM_SERVER_URL=http://localhost:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - elasticsearch
