FROM node:alpine

RUN apk update && apk add --no-cache nodejs && corepack enable
RUN addgroup jobber && adduser -S -G jobber api-gateway

USER api-gateway

WORKDIR /api-gateway

COPY package.json tsconfig.json .npmrc ./
COPY src ./src

RUN ls -a
RUN pnpm install

EXPOSE 4000

CMD [ "pnpm", "dev" ]

