FROM node:alpine

RUN apk update && apk add --no-cache nodejs && corepack enable
RUN addgroup jobber && adduser -S -G jobber api-gateway

USER api-gateway

WORKDIR /api-gateway

COPY package.json tsconfig.json .npmrc ./
COPY src ./src

USER root

RUN chown -R api-gateway:jobber .

USER api-gateway

RUN ls -a
RUN pnpm install
RUN rm -f .npmrc

EXPOSE 4000

CMD [ "pnpm", "dev" ]