services:
  users:
    container_name: users
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4003:4003
    env_file: .env.development.local
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: curl -f http://localhost:4003/user-health || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
    volumes:
      - .:/users
      - /users/node_modules
    networks:
      - jobber_app
