FROM node:alpine

RUN apk update && apk add --no-cache nodejs && corepack enable
RUN addgroup jobber && adduser -S -G jobber users

USER users

WORKDIR /users

COPY package.json tsconfig.json .npmrc ./
COPY src ./src

USER root

RUN chown -R users:jobber .

USER users

RUN ls -a
RUN pnpm install
RUN rm -f .npmrc

EXPOSE 4003

CMD [ "pnpm", "dev" ]