name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [23.x]
      # Add fail-fast to prevent all matrix jobs from failing if one fails
      fail-fast: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Fetch all history for better versioning
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path | tr -d '\n')" >> $GITHUB_ENV

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          # Enable caching of npm dependencies
          cache: 'pnpm'

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      # Add environment variables validation
      - name: Validate Environment Variables
        run: |
          if [ -z "${{ secrets.GITHUB_TOKEN }}" ]; then
            echo "Error: GITHUB_TOKEN is not set"
            exit 1
          fi

      - name: Set npm private registry token
        run: |
          echo "@francislagares:https://npm.pkg.github.com/ > ~/.npmrc"
          echo "//npm.pkg.github.com/:_authToken=NPM_TOKEN" >> ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Dependencies
        run: pnpm install
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Prisma ORM schema to the database
        run: pnpm prisma migrate deploy

      - name: Run Tests
        run: pnpm test:ci
        env:
          CI: true